version: "3"
services:
  rce-backend:
    image: rce-backend-image # Replace with your Docker image name for the backend
    build: .
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
    deploy:
      replicas: 3 # Scale to 3 backend instances
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
